stages:
  - build
  - release

# Build job - runs only when a tag is created
build:
  stage: build
  image: node:22-alpine
  tags:
    - docker
  only:
    - tags
  before_script:
    - apk add --no-cache zip
  script:
    - npm install
    - npm run build
    - cd dist
    - zip -r ../sussex-devtools.zip .
  artifacts:
    paths:
      - sussex-devtools.zip
    expire_in: 1 week

# Release job - creates GitLab release with the build artifact
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - docker
  only:
    - tags
  needs:
    - build
  script:
    - echo "Creating release for $CI_COMMIT_TAG"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG - Sussex DevTools Chrome Extension'
    assets:
      links:
        - name: 'sussex-devtools.zip'
          url: '$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/raw/sussex-devtools.zip?job=build'
